apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: mark888899/shoppingcart:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/shoppingcart"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-service
spec:
  selector:
    app: shoppingcart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
